### ISSUE TITLE
Portals through dimensions

### ISSUE THREAD

**Issue by detective-wraith** [MeowMC/PortalGun#1]
Description: Portals can go through dimensions

Steps to Reproduce:
1. Grab an Aperture Science Handheld Dual-Portal Device.
2. Build a Nether Portal, preferably one you can fit through.
3. Go to the Nether.
4. Shoot a portal or 2. 
5. Leave the Nether.
6. Press the Portal clearing key bind
7. Shoot a new portal in the overworld.

Results: A portal to the Nether

Expected Results: A portal that does not lead to the nether.

**Comment by MeowMC** [comment]
Should be fixed in v1.1.0

**Comment by MeowMC** [comment]
fixed
