### ISSUE TITLE
Multiplayer Crashing

### ISSUE THREAD

**Issue by Wactus** [MeowMC/PortalGun#11]
I used a fabric server and open to LAN and when someone joins the server their game crashes

**Comment by MeowMC** [comment]
Can you send the crash report?(Put in a pastebin or smth)

**Comment by Wactus** [comment]
Here is a pastebin link to the crash report https://pastebin.com/WsxL6LJ5
(I am on v1.1.6)

**Comment by MeowMC** [comment]
Is this a dedicated server or just you opening a world to LAN and using something like Hamachi?

**Comment by MeowMC** [comment]
Try this: https://github.com/MeowMC/PortalGun/releases/tag/v1.1.7

**Comment by Wactus** [comment]
I get the same results on a fabric server and LAN world, even after I update to v1.1.7, here is the crash report 
https://pastebin.com/pnE9V6V7
 
(When I use the LAN world only the people the join my world crash, not me)

**Comment by MeowMC** [comment]
try this https://github.com/MeowMC/PortalGun/releases/tag/v1.1.8

**Comment by MeowMC** [comment]
I didn't bump the version internally cuz I forgot but yeah

**Comment by Wactus** [comment]
It doesn't crash when I join the world, but it still crashes when I use the portal gun.

(Crash report: https://pastebin.com/gWYQbLQ3)

**Comment by MeowMC** [comment]
should be fixed
