### ISSUE TITLE
Client disconnected from server when shooting portal, server sometimes crashes

### ISSUE THREAD

**Issue by Invictable** [MeowMC/PortalGun#15]
I setup a basic fabric server, when I shoot the portal gun I get disconnected. a few times while trying this the server crashed. The client never crashed, it just disconnected me. 

Here's the server crash report: https://hastebin.com/xacayapari
Here's the client log: https://hastebin.com/utiqujoxut
Here's what the server shows when I disconnect and the server doesn't crash: https://hastebin.com/isubekipeb

Also on a LAN world with a second account, only the host of the world can make a portal.

**Comment by MeowMC** [comment]
LAN worlds are a bit scuffed in their own right but I'm not sure why that's happening on the dedicated server

**Comment by MeowMC** [comment]
Might be fixed in v1.2.4

**Comment by MeowMC** [comment]
Fixed in v1.2.5 (I tested it)
