### ISSUE TITLE
Infi-portal

### ISSUE THREAD

**Issue by detective-wraith** [MeowMC/PortalGun#2]
Descriptions: A glitch that allows for infinite portals to exist

Steps to Reproduce: 
1. Grab your Aperture Science Handheld Dual-Portal Device
2. Rapidly use Right or Left click to make portals

Results: 
Occasionally, A portal will stay instead of disappearing like it should

Expected Results: 
The portals should all disappear.

**Comment by MeowMC** [comment]
might be fixed in v1.0.8

**Comment by MeowMC** [comment]
should be fixed in v1.0.9 or higher

**Comment by MeowMC** [comment]
fixed
