### ISSUE TITLE
Horizontal Portal Rotation

### ISSUE THREAD

**Issue by Aresiel** [MeowMC/PortalGun#3]
The rotation for horizontal portals is always the same. I presume this will be relatively simple to fix since there's probably well-thought-out and methodic logic deciding the portal's rotations.

**Comment by Aresiel** [comment]
That is not an enhancement exucuse me

**Comment by MeowMC** [comment]
> That is not an enhancement exucuse me

Not a bug ¯\_(ツ)_/¯

**Comment by Aresiel** [comment]
It may not be a bug but it is a flaw, a very important flaw that needs immediate attention.

**Comment by MeowMC** [comment]
> It may not be a bug but it is a flaw, a very important flaw that needs immediate attention.

Sorry there's no "flaw" tag

**Comment by Aresiel** [comment]
Don't worry, it is really easy to create one. https://stackoverflow.com/a/29223259

**Comment by MeowMC** [comment]
> Don't worry, it is really easy to create one. https://stackoverflow.com/a/29223259

I know how I was just trying to get you to shut up about it

**Comment by Aresiel** [comment]
No need to worry, I'm adamant about it.

**Comment by Aresiel** [comment]
Update: Part of the problem outsourced the problem to IP.

**Comment by MalekiRe** [comment]
Implemented!

**Comment by MeowMC** [comment]
oh thanks I meant to do that lmao
