### ISSUE TITLE
Portal Gun 1.18.1 version not on Curseforge

### ISSUE THREAD

**Issue by Gamerbolts** [MeowMC/PortalGun#31]
Hello!, I tried putting your mod into my 1.18.1 pack and I got it from Curseforge. This is the version it gave me for 1.18.2 and there is no other versions.

![image](https://user-images.githubusercontent.com/20451601/161609317-314627c0-6493-417f-a0d9-95af53b931d1.png)

Can I download the 1.18.1 version from the website and put it in my pack and upload the modpack to curseforge without any problems?

**Comment by froyo4u** [comment]
The 1.18.2 version should work with 1.18.1

**Comment by Gamerbolts** [comment]
I tried it and it didn't get past the initial loading. No crash but here is the latest log
[latest.log](https://github.com/MeowMC/PortalGun/files/8412320/latest.log)

**Comment by froyo4u** [comment]
oops, the version of Immersive Portals I supply in my mod isn't compatible with 1.18.1, install this: https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod/files/3622902 and it'll override the version I include.
Keep me posted!

**Comment by Gamerbolts** [comment]
ok will do! Ty

**Comment by Gamerbolts** [comment]
[latest.log](https://github.com/MeowMC/PortalGun/files/8412356/latest.log)
Still crashed with Imm Portals 1.2.5 installed

**Comment by froyo4u** [comment]
oh y'know what, I think mine might actually be overriding what immersive portals supplies because mine is a higher version number. I'll go make you a 1.18.1 version, sorry about that

**Comment by Gamerbolts** [comment]
Not a problem :) Thanks for the help!

**Comment by froyo4u** [comment]
the 1.18.1 version was uploaded to curseforge a couple minutes ago, waiting for it to be approved rn

**Comment by froyo4u** [comment]
it's been approved. here you go!
https://www.curseforge.com/minecraft/mc-mods/portal-gun-fabric/files/3735378

should work

**Comment by Gamerbolts** [comment]
Really wish I could say it worked...
[latest.log](https://github.com/MeowMC/PortalGun/files/8412521/latest.log)

Sorry I am so difficult and by me I mean my modpack :D

**Comment by froyo4u** [comment]
oh ik the issue lol

**Comment by froyo4u** [comment]
I think

**Comment by froyo4u** [comment]
currently uploading a new one, I deleted the old version. Hope this one works

**Comment by froyo4u** [comment]
note: the reason it didn't work is because I didn't feel like opening the game lmfao

**Comment by froyo4u** [comment]
bruh nvm they rejected it because it's a "duplicate"

**Comment by froyo4u** [comment]
literally deleted the old one but ok

**Comment by froyo4u** [comment]
let's try this again

**Comment by Gamerbolts** [comment]
lol that is weird. ok ty

**Comment by froyo4u** [comment]
https://www.curseforge.com/minecraft/mc-mods/portal-gun-fabric/files/3735395

**Comment by Gamerbolts** [comment]
That worked! Thanks so much.

**Comment by froyo4u** [comment]
awesome! Glad I could help
