### ISSUE TITLE
Portal Moves on its own

### ISSUE THREAD

**Issue by jeffboy70** [MeowMC/PortalGun#5]
Descriptions: Portal moves when one is in the overworld and the other is in the nether

Steps to Reproduce:

Shoot one portal in the overworld, then go into the nether and shoot a portal in there.
Go through the portal in the nether and then back through again a couple times
Results:
The portal in the nether should teleport into the overworld

Expected Results:
It should not move dimensions

**Comment by MeowMC** [comment]
should be fixed in v1.1.0

**Comment by MeowMC** [comment]
fixed
