### ISSUE TITLE
Incorrect Placement of Horizontal Portals

### ISSUE THREAD

**Issue by MalekiRe** [MeowMC/PortalGun#9]
If you aim just on the edge of a block, you can create a horizontal portal on a ledge, so that half of it is on top of nothing, unlike with vertical portals, where you can only create a portal if there are two supporting blocks behind the portal.

**Comment by MeowMC** [comment]
Who tf is gonna be placing a portal at the EDGE of a block dude

**Comment by MeowMC** [comment]
I mean I'll try and fix it but com'on man

**Comment by MeowMC** [comment]
I fixed it
